name: LaurenStGeorge
favicon: null
layout_spectrum: 0.73874
typography_spectrum: 0.15202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d32437'
    - '#f48c32'
    - '#30a792'
    - '#532971'
  brandStrength: 0.5
  lightness: 0.7758286632597446
  saturation: 0.0476158712990582
  rhythmicContrast: 0.5752665225882083
purpose: []
